config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  post 'import', to: 'home#import'
  get 'import_purchase_with_success/:id', to: 'import_purchases#import_purchase_with_success', as: :import_purchase_with_success
  get 'import_purchase_with_error/:id', to: 'import_purchases#import_purchase_with_error', as: :import_purchase_with_error

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import_purchase.rb
class ImportPurchase < ApplicationRecord
	belongs_to :user
	has_many :import_purchase_lines
	has_attached_file :import_file

	validates :import_file, attachment_presence: true
	do_not_validate_attachment_file_type :import_file
	validates :user_id, presence: true

	before_create :set_initial_status
	after_create_commit :import_in_background

	def import_purchase_lines_in_background
		self.update_attribute(:status, :running)
		File.open(self.import_file.path).each_with_index do |line, i|
			next if i == 0
			import_purchase_line = self.import_purchase_lines.build
			if import_purchase_line.import_line(line)
				self.update_attribute(:lines_with_success, self.lines_with_success.to_i + 1)
			else
				self.update_attribute(:lines_with_errors, self.lines_with_errors.to_i + 1)
			end
			self.update_attribute(:lines_importeds, self.lines_importeds.to_i + 1)
		end
		self.update_attribute(:status, :finished)
	end

	private
		def import_in_background
			ImportPurchaseJob.perform_later(self.id)
		end

		def set_initial_status
			self.status = :initialized
		end
end

app/models/import_purchase_line.rb
class ImportPurchaseLine < ApplicationRecord
	scope :with_errors, -> { where("result IS NOT NULL") }
	scope :with_success, -> { where("result IS NULL") }
	belongs_to :import_purchase
	validates :purchaser_name, :item_description, :merchant_address, :merchant_name, presence: true
	validates :item_price, :purchase_count, numericality: true, presence: true


	def import_line(line)
		return false if line.to_s.blank?
		data = line.split(/\t/)
		self.purchaser_name = data[0]
		self.item_description = data[1]
		self.item_price = data[2]
		self.purchase_count = data[3]
		self.merchant_address = data[4]
		self.merchant_name = data[5]
		self.total = self.item_price.to_f * self.purchase_count.to_i
		self.import_purchase.update_attribute(:total, self.total + self.import_purchase.total.to_f)
		if self.save
			true
		else
			self.valid?
			self.result = self.errors.full_messages.join(", ")
			self.save(validate: false)
			false
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  has_many :import_purchases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :set_import_purchase, only: :index
	before_action :set_import_purchase_with_params, only: :import
	before_action :set_import_purchases

	def index
		scheduler = Rufus::Scheduler.new
		scheduler.every '5s' do
			import_purchases = []
			if @import_purchases.where("status != ?",:finished).count > 0
				@import_purchases.where("status != ?",:finished).each do |import_purchase|
					import_purchases << {
						id: import_purchase.id,
						lines_with_success: import_purchase.lines_with_success,
						lines_with_errors: import_purchase.lines_with_errors,
						lines_importeds: import_purchase.lines_importeds,
						updated_at: I18n.l(import_purchase.updated_at, format: :short),
						total: ActionController::Base.helpers.number_to_currency(import_purchase.total),
						status: t("import_status.#{import_purchase.status.to_s}"),
					}
				end
				ActionCable.server.broadcast("import_purchase_lines_channel",
					import_purchases: import_purchases
				)
			else
				scheduler.stop
			end
		end
	end

	def import
		if @import_purchase.save
			redirect_to root_path, notice: t('forms.messages.operation_with_success')
		else
			flash[:error] = t('forms.messages.operation_with_error')
			render :index
		end
	end

	private
		def import_purchase_params
			params.require(:import_purchase).permit(:import_file, :user_id)
		end

		def set_import_purchase
			@import_purchase = ImportPurchase.new
		end

		def set_import_purchases
			@import_purchases = ImportPurchase.order("id DESC").page(params[:page])
		end

		def set_import_purchase_with_params
			@import_purchase = ImportPurchase.new(import_purchase_params)
		end
end

app/controllers/import_purchases_controller.rb
class ImportPurchasesController < ApplicationController
  before_action :set_import_purchase

  def import_purchase_with_success
    @import_purchase_lines = @import_purchase.import_purchase_lines.with_success.page(params[:page])
    render :import_purchase_with_success
  end

  def import_purchase_with_error
    @import_purchase_lines = @import_purchase.import_purchase_lines.with_errors.page(params[:page])
    render :import_purchase_with_error
  end

  private
    def set_import_purchase
      @import_purchase = ImportPurchase.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/import_purchases_helper.rb
module ImportPurchasesHelper
  def status_of_import_purchase(status)
    t("import_status.#{status}")
  end

  def merchant_address_info(import_purchase_line)
  	t('merchant_address_info', merchant_name: (import_purchase_line.merchant_name || t('merchant_without_name')), merchant_address: import_purchase_line.merchant_address || t('merchant_without_address'))
  end

  def merchant_price(import_purchase_line)
  	return if import_purchase_line.item_price.blank?
  	number_to_currency(import_purchase_line.item_price)
  end
end

app/views/home/_import_purchase.html.erb
<tr id="import_purchase_<%=import_purchase.id%>">
  <td><%=import_purchase.id%></td>
  <td><%=import_purchase.user.name%></td>
  <td id="import_purchase_lines_status_<%=import_purchase.id%>"><%= status_of_import_purchase(import_purchase.status) %></td>
  <td><%=import_purchase.import_file.original_filename%></td>
  <td id="import_purchase_lines_importeds_<%=import_purchase.id%>"><%=import_purchase.lines_importeds %></td>
  <td id="import_purchase_lines_with_success_<%=import_purchase.id%>"><%=link_to_unless(import_purchase.lines_with_success.nil?, import_purchase.lines_with_success, import_purchase_with_success_path(import_purchase)) %></td>
  <td id="import_purchase_lines_with_errors_<%=import_purchase.id%>"><%=link_to_unless(import_purchase.lines_with_errors.nil?, import_purchase.lines_with_errors, import_purchase_with_error_path(import_purchase)) %></td>
  <td id="import_purchase_lines_total_<%=import_purchase.id%>"><%=number_to_currency import_purchase.total.to_f %></td>
  <td><%=l import_purchase.created_at, format: :short %></td>
  <td><%=l import_purchase.updated_at, format: :short %></td>
</tr>

app/views/home/index.html.erb
<h1><%= t('informations_to_import') %></h1>
<%= simple_form_for @import_purchase, url: import_path do |f| %>
  <%= f.association :user %>
  <%= f.input :import_file %>
  <%= f.button :submit %>
<% end %>
<hr />
<h3><%=t('informations_of_imports')%></h3>
<%= paginate @import_purchases %>
<table class="table table-bordered">
  <thead>
    <th><%=ImportPurchase.human_attribute_name(:id)%></th>
    <th><%=ImportPurchase.human_attribute_name(:user)%></th>
    <th><%=ImportPurchase.human_attribute_name(:status)%></th>
    <th><%=ImportPurchase.human_attribute_name(:import_file)%></th>
    <th><%=ImportPurchase.human_attribute_name(:lines_importeds)%></th>
    <th><%=ImportPurchase.human_attribute_name(:lines_withu_success)%></th>
    <th><%=ImportPurchase.human_attribute_name(:lines_with_errors)%></th>
    <th><%=ImportPurchase.human_attribute_name(:total)%></th>
    <th><%=ImportPurchase.human_attribute_name(:created_at)%></th>
    <th><%=ImportPurchase.human_attribute_name(:updated_at)%></th>
  </thead>
  <tbody>
  <% @import_purchases.each do |import_purchase| %>
    <%= render "import_purchase", import_purchase: import_purchase %>
  <% end -%>
  </tbody>
</table>
<%= paginate @import_purchases %>

app/views/import_purchases/_import_purchase_line.html.erb
<tr>
  <td><%= import_purchase_line.import_purchase.user.name %></td>
  <td><%= import_purchase_line.purchaser_name %></td>
  <td><%= import_purchase_line.item_description %></td>
  <td><%= merchant_price(import_purchase_line) %></td>
  <td><%= import_purchase_line.purchase_count %></td>
  <td><%= merchant_address_info(import_purchase_line) %></td>
  <td><%= import_purchase_line.result %></td>
</tr>

app/views/import_purchases/_import_purchase_table.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="col-md-1"><%= ImportPurchase.human_attribute_name(:user) %></th>
      <th class="col-md-2"><%= ImportPurchaseLine.human_attribute_name(:purchaser_name) %></th>
      <th class="col-md-1"><%= ImportPurchaseLine.human_attribute_name(:item_description) %></th>
      <th class="col-md-1"><%= ImportPurchaseLine.human_attribute_name(:item_price) %></th>
      <th class="col-md-1"><%= ImportPurchaseLine.human_attribute_name(:purchase_count) %></th>
      <th class="col-md-2"><%= ImportPurchaseLine.human_attribute_name(:merchant_name) %></th>
      <th class="col-md-2"><%= ImportPurchaseLine.human_attribute_name(:result) %></th>
    </tr>
  </thead>
  <tbody>
    <% @import_purchase_lines.each do |import_purchase_line| %>
      <%= render "import_purchase_line", import_purchase_line: import_purchase_line %>
    <% end -%>
  </tbody>
</table>

app/views/import_purchases/import_purchase_with_error.html.erb
<h1><%= t('import_purchase_with_error', import_purchase_id: @import_purchase.id, created_at: l(@import_purchase.created_at, format: :short)) %></h1>
<%= paginate @import_purchase_lines %>
<%= render 'import_purchase_table' %>
<%= paginate @import_purchase_lines %>

app/views/import_purchases/import_purchase_with_success.html.erb
<h1><%= t('import_purchase_with_success', import_purchase_id: @import_purchase.id, created_at: l(@import_purchase.created_at, format: :short)) %></h1>
<%= paginate @import_purchase_lines %>
<%= render 'import_purchase_table' %>
<%= paginate @import_purchase_lines %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only"><%=t('header.hide')%></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('header.home'), root_path, data: { turbolinks: false }, class: 'navbar-brand' if user_signed_in? %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to(t('devise.sessions.sign_out'), destroy_user_session_path, method: :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to(t('devise.sessions.sign_in'), new_user_session_path)  %>
  </li>
  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <li>
      <%= link_to t('forgot_password'), new_password_path(resource_name) %>
  </li>
  <% end -%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t(:application_name) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Desafio Programacao" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>